Update release.yaml

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -122,8 +122,21 @@ jobs:
 
       - name: Upload CloudFormation Lambda ZIP and SAM templates to S3
         run: |
-          aws s3 cp ./cfn-lambda.zip s3://logzio-aws-integrations-${{ matrix.aws_region }}/firehose-logs/${{ github.event.release.tag_name }}/cfn-lambda.zip --acl public-read
-          aws s3 cp ./eventbridge-lambda.zip s3://logzio-aws-integrations-${{ matrix.aws_region }}/firehose-logs/${{ github.event.release.tag_name }}/eventbridge-lambda.zip --acl public-read
+          if [ -f ./cfn-lambda.zip ]; then
+            aws s3 cp ./cfn-lambda.zip s3://logzio-aws-integrations-${{ matrix.aws_region }}/firehose-logs/${{ github.event.release.tag_name }}/cfn-lambda.zip --acl public-read
+          else
+            echo "cfn-lambda.zip not found, skipping upload."
+            exit 1
+          fi
+          
+          # Upload the EventBridge Lambda ZIP to S3
+          if [ -f ./eventbridge-lambda.zip ]; then
+            aws s3 cp ./eventbridge-lambda.zip s3://logzio-aws-integrations-${{ matrix.aws_region }}/firehose-logs/${{ github.event.release.tag_name }}/eventbridge-lambda.zip --acl public-read
+          else
+            echo "eventbridge-lambda.zip not found, skipping upload."
+            exit 1
+          fi 
+          
           aws s3 cp ./sam-template-${{ matrix.aws_region }}.yaml s3://logzio-aws-integrations-${{ matrix.aws_region }}/firehose-logs/${{ github.event.release.tag_name }}/sam-template.yaml --acl public-read
 
       # Clean up the workspace
